#!/bin/sh

bsptags_location=~/.scripts/bsptags/bsptags

function toggle() {
  if [ "$1" -eq 0 ]; then
    echo "Argument equals 0"
    if ! grep -qE '[0-9]+ - ' /tmp/bspwm_window_info; then
      echo "File is empty"
      $bsptags_location 0 >> /dev/null
      return
    else 
      echo "File is not empty"
      $bsptags_location -b 0 >> /dev/null
      echo "" > /tmp/bspwm_window_info
      return
    fi 
  else
    if grep -e "$1 -" /tmp/bspwm_window_info; then
      $bsptags_location -b "$1" >> /dev/null
    else
      $bsptags_location "$1" >> /dev/null
    fi
  fi
}

toggle $1
